/**
 * @file BaseLock 锁
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'base-lock',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '7ed1a0ac'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '7ed1a0ac' + ')'}
            >
                <g>
                    <path
                        d="M8,0.5C6.067,0.499999656677,4.499999694824,2.067,4.5,4L4.5,6L11.5,6L11.5,4C11.5,2.067,9.933,0.499999885559,8,0.5ZM8.1085,1.5025C9.44578,1.56067,10.5,2.66162,10.5,4L10.5,5L5.5,5L5.5,4C5.499999,2.61929,6.6192899999999995,1.5,8,1.5L8.1085,1.5025Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M12.5,5L3.5,5C2.671573,5.000000305176,2.000000152588,5.671573,2,6.5L2,14C2.000000152588,14.82843,2.671573,15.5,3.5,15.5L12.5,15.5C13.3284,15.5,14,14.82843,14,14L14,6.5C14,5.671573,13.3284,5.000000305176,12.5,5ZM3.5,6L12.5,6C12.7761,6,13,6.22386,13,6.5L13,14C13,14.27614,12.7761,14.5,12.5,14.5L3.5,14.5C3.22386,14.5,3,14.27614,3,14L3,6.5C3,6.22386,3.22386,6,3.5,6Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M8.5,9L8.5,11.5L7.5,11.5L7.5,9L8.5,9Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
