/**
 * @file BaseSave 保存
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'base-save',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + 'fcc81eaf'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + 'fcc81eaf' + ')'}
            >
                <g>
                    <path
                        d="M11,8.5L5,8.5L5,14.5L11,14.5L11,8.5ZM10,9.5L10,13.5L6,13.5L6,9.5L10,9.5ZM5,1.5L5,5.5L11,5.5L11,2.5C11,1.947715,10.55229,1.5,10,1.5L5,1.5ZM6,4.5L6,2.5L10,2.5L10,4.5L6,4.5Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M10.586,1.5L3,1.5C2.171573,1.499999847412,1.5,2.171573,1.5,3L1.5,13C1.5,13.8284,2.171573,14.5,3,14.5L13,14.5C13.8284,14.5,14.5,13.8284,14.5,13L14.5,5.414C14.4998,5.01638,14.3417,4.635120000000001,14.0605,4.354L11.6465,1.939C11.36529,1.657907,10.98384,1.5,10.586,1.5ZM3,2.5L10.586,2.5C10.7186,2.5000299999999998,10.84575,2.55273,10.9395,2.6465L13.3535,5.0605C13.4473,5.154310000000001,13.5,5.2814700000000006,13.5,5.414L13.5,13C13.5,13.2761,13.2761,13.5,13,13.5L3,13.5C2.72386,13.5,2.5,13.2761,2.5,13L2.5,3C2.5,2.72386,2.72386,2.5,3,2.5Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
