/**
 * @file BaseStop 停止
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'base-stop',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <g>
                <g style={{opacity: 0}}>
                    <path
                        d="M0,0L16,0L16,16L0,16L0,0Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M8,1C4.13401,1,1,4.13401,1,8C1,11.866,4.13401,15,8,15C11.866,15,15,11.866,15,8C15,4.13401,11.866,1,8,1ZM8,2C11.3137,2,14,4.68629,14,8C14,11.3137,11.3137,14,8,14C4.68629,14,2,11.3137,2,8C2,4.68629,4.68629,2,8,2Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M6.5,6L9.5,6C9.77614,6,10,6.223858,10,6.5L10,9.5C10,9.77614,9.77614,10,9.5,10L6.5,10C6.223858,10,6,9.77614,6,9.5L6,6.5C6,6.223858,6.223858,6,6.5,6Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
