/**
 * @file BasePause 暂停
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'base-pause',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <g>
                <g>
                    <g style={{opacity: 0}}>
                        <path
                            d="M0,0L16,0L16,16L0,16L0,0Z"
                            fill={props.colors[0]}
                            fill-opacity="1"
                        />
                    </g>
                    <g>
                        <path
                            d="M8,1C4.13401,1,1,4.13401,1,8C1,11.866,4.13401,15,8,15C11.866,15,15,11.866,15,8C15,4.13401,11.866,1,8,1ZM8,2C11.3137,2,14,4.68629,14,8C14,11.3137,11.3137,14,8,14C4.68629,14,2,11.3137,2,8C2,4.68629,4.68629,2,8,2Z"
                            fill={props.colors[0]}
                            fill-opacity="1"
                        />
                    </g>
                </g>
                <g>
                    <g>
                        <path
                            d="M7,6L7,10L6,10L6,6L7,6Z"
                            fill={props.colors[0]}
                            fill-opacity="1"
                        />
                    </g>
                    <g>
                        <path
                            d="M10,6L10,10L9,10L9,6L10,6Z"
                            fill={props.colors[0]}
                            fill-opacity="1"
                        />
                    </g>
                </g>
            </g>
        </svg>
    )
);
