/**
 * @file BaseSendShare 分享1
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'base-send-share',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '341ab228'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '341ab228' + ')'}
            >
                <g>
                    <path
                        d="M8,1.5L8,2.5L3,2.5C2.74651,2.5000299999999998,2.53316,2.68975,2.5035,2.9415L2.5,3L2.5,13C2.5000299999999998,13.2535,2.68975,13.4668,2.9415,13.4965L3,13.5L13,13.5C13.2535,13.5,13.4668,13.3102,13.4965,13.0585L13.5,13L13.5,8L14.5,8L14.5,13C14.5,13.7943,13.8809,14.4509,13.088,14.4975L13,14.5L3,14.5C2.205721,14.5,1.5490973,13.8809,1.5025,13.088L1.5,13L1.5,3C1.4999559021,2.20572,2.11909,1.549097,2.912,1.5025L3,1.5L8,1.5ZM14,1.5C14.2535,1.5000332642,14.4668,1.689753,14.4965,1.9415L14.5,2L14.5,6L13.5,6L13.5,2.5L10,2.5L10,1.5L14,1.5Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M13.312984375,1.97998046875L14.019984375,2.68698046875L8.353484375,8.35348046875L7.646484375,7.64648046875L13.312984375,1.97998046875Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
