/**
 * @file CircleCheck 选中
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'circle-check',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + 'ef563493'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + 'ef563493' + ')'}
            >
                <g>
                    <path
                        d="M1,8C1,4.134,4.134,1,8,1C11.866,1,15,4.134,15,8C15,11.866,11.866,15,8,15C4.134,15,1,11.866,1,8ZM14,8C14,4.6865000000000006,11.3135,2,8,2C4.6865000000000006,2,2,4.6865000000000006,2,8C2,11.3135,4.6865000000000006,14,8,14C11.3135,14,14,11.3135,14,8ZM11.3855,6L10.434,6L7.4755,8.644L5.9615,7.6115L5,7.6115L7.4755,10.192L11.3855,6Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
