/**
 * @file ColorfulTemplate 模板
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'colorful-template',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
        >
            <defs>
                <linearGradient
                    x1="0.6672566533088684"
                    y1="-0.5060058832168579"
                    x2="0.2416876238590574"
                    y2="1.032976530850613"
                    id={props.id + '34aedaf0'}
                >
                    <stop
                        offset="0%"
                        stop-color="#1DD4FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="94.81717348098755%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                </linearGradient>
                <filter
                    id={props.id + 'd9e7072b'}
                    filterUnits="objectBoundingBox"
                    color-interpolation-filters="sRGB"
                    x="0"
                    y="0"
                    width="1"
                    height="1"
                >
                    <feFlood
                        flood-opacity="0"
                        result="BackgroundImageFix"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                    />
                    <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="2.0399999618530273"
                    />
                    <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_foregroundBlur"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_foregroundBlur"
                        result="shape"
                    />
                </filter>
                <filter
                    id={props.id + '809ff016'}
                    filterUnits="objectBoundingBox"
                    color-interpolation-filters="sRGB"
                    x="0"
                    y="0"
                    width="1"
                    height="1"
                >
                    <feFlood
                        flood-opacity="0"
                        result="BackgroundImageFix"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                    />
                    <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="2.0399999618530273"
                    />
                    <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_foregroundBlur"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_foregroundBlur"
                        result="shape"
                    />
                </filter>
            </defs>
            <g>
                <g style={{opacity: 0}}>
                    <rect
                        x="0"
                        y="0"
                        width="24"
                        height="24"
                        rx="0"
                        fill="#D8D8D8"
                        fill-opacity="1"
                    />
                </g>
                <g style={{opacity: 0}}>
                    <rect
                        x="0"
                        y="0"
                        width="24"
                        height="24"
                        rx="0"
                        fill="#D8D8D8"
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M3,7.5L3,17.8C3,19.5673,4.43269,21,6.2,21L17.8,21C19.5673,21,21,19.5673,21,17.8L21,7.5C21,6.947715,20.5523,6.5,20,6.5L12,6.5L4,6.5C3.447715,6.5,3,6.947715,3,7.5Z"
                        fill={'url(#' + props.id + '34aedaf0' + ')'}
                        fill-opacity="1"
                    />
                </g>
                <g
                    filter={'url(#' + props.id + 'd9e7072b' + ')'} style={{opacity: 0.9599999785423279}}
                >
                    <path
                        d="M3,6.2L3,8L21,8L21,6.2C21,4.43269,19.5673,3,17.8,3L12,3L6.2,3C4.43269,3,3,4.43269,3,6.2Z"
                        fill="#AED6FF"
                        fill-opacity="1"
                    />
                </g>
                <g
                    filter={'url(#' + props.id + '809ff016' + ')'} style={{opacity: 0.9599999785423279}}
                >
                    <path
                        d="M5,11L5,17C5,18.104570000000002,5.89543,19,7,19C8.104569999999999,19,9,18.104570000000002,9,17L9,11C9,10.447715,8.55228,10,8,10L7,10L6,10C5.447715,10,5,10.447715,5,11Z"
                        fill="#AED6FF"
                        fill-opacity="1"
                    />
                </g>
                <g
                    transform="matrix(1,-2.2348338291067193e-8,2.2348338291067193e-8,1,-2.681800594928063e-7,2.681800594928063e-7)"
                >
                    <path
                        d="M17.99121,12.75C17.99121,13.16421,17.65542,13.5,17.24121,13.5L12.75,13.5C12.335786,13.5,12,13.16421,12,12.75C12,12.335786,12.335786,12,12.75,12L17.24121,12C17.65542,12,17.99121,12.335786,17.99121,12.75"
                        fill={props.colors[2]}
                        fill-opacity="1"
                    />
                </g>
                <g
                    transform="matrix(1,-2.2348338291067193e-8,2.2348338291067193e-8,1,-3.575734126570751e-7,2.681800594928063e-7)"
                >
                    <path
                        d="M17.99121,16.75C17.99121,17.16421,17.65542,17.5,17.24121,17.5L12.75,17.5C12.335786,17.5,12,17.16421,12,16.75C12,16.335786,12.335786,16,12.75,16L17.24121,16C17.65542,16,17.99121,16.335786,17.99121,16.75"
                        fill={props.colors[2]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
