/**
 * @file DocumentUploadSimple 上传
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'document-upload-simple',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '40b89660'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '40b89660' + ')'}
            >
                <g>
                    <path
                        d="M1.5,11.499773125L2.5,11.499773125L2.5,12.999803125C2.5000299999999998,13.253303125,2.68975,13.466603125,2.9415,13.496303125L3,13.499803125L13,13.499803125C13.2535,13.499703125,13.4668,13.310003125,13.4965,13.058303125L13.5,12.999803125L13.5,11.499773125L14.5,11.499773125L14.5,12.999803125C14.5,13.794003125,13.8809,14.450703125,13.088,14.497303125L13,14.499803125L3,14.499803125C2.205721,14.499803125,1.5490973,13.880703125,1.5025,13.087803125L1.5,12.999803125L1.5,11.499773125ZM7.5885,1.679771125C7.76777,1.500382425,8.05295,1.483619825,8.251999999999999,1.640771125L8.2955,1.679771125L13.124,6.508273125L12.417,7.215273125L7.942,2.740273125L3.467,7.215273125L2.76,6.508273125L7.5885,1.679771125Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M8.44140625,2.4150390625L8.44140625,11.9150390625L7.44140625,11.9150390625L7.44140625,2.4150390625L8.44140625,2.4150390625Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
