/**
 * @file DocumentMenu 目录文件
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'document-menu',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '1d873d92'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '1d873d92' + ')'}
            >
                <g style={{opacity: 0.8999999761581421}}>
                    <path
                        d="M3.5,1L12.5,1C13.3284,1,14,1.671573,14,2.5L14,13.5C14,14.3284,13.3284,15,12.5,15L3.5,15C2.671573,15,2,14.3284,2,13.5L2,2.5C2,1.671573,2.671573,1,3.5,1ZM12.5,2L3.5,2C3.22386,2,3,2.22386,3,2.5L3,13.5C3,13.7761,3.22386,14,3.5,14L12.5,14C12.7761,14,13,13.7761,13,13.5L13,2.5C13,2.22386,12.7761,2,12.5,2ZM11.25,5L11.25,4L4.75,4L4.75,5L11.25,5ZM8.75,7.5L8.75,6.5L4.75,6.5L4.75,7.5L8.75,7.5Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
