/**
 * @file DocumentExit 退出
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'document-exit',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + 'cfd37137'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + 'cfd37137' + ')'}
            >
                <g>
                    <path
                        d="M1.50199997,2.9085C1.5364999,2.151,1.9965,1.5,2.6665,1.5L9.333,1.5L9.413,1.50300003C10.066,1.5545,10.5,2.235,10.5,3L10.5,5.75L9.5,5.75L9.5,3L9.497499999999999,2.925C9.4795,2.6605,9.369,2.5,9.3335,2.5L2.6665,2.5L2.6550000000000002,2.504C2.607,2.5324999999999998,2.5,2.717,2.5,3L2.5,13L2.5025,13.075C2.5205,13.3395,2.6310000000000002,13.5,2.6665,13.5L9.3335,13.5L9.344999999999999,13.496C9.393,13.4675,9.5,13.283,9.5,13L9.5,10.25L10.5,10.25L10.5,13L10.498,13.0915C10.4635,13.849,10.0035,14.5,9.3335,14.5L2.667,14.5L2.5869999999999997,14.497C1.934,14.4455,1.5,13.765,1.5,13L1.5,3L1.50199997,2.9085ZM15.1005,8.242C15.2577,8.042950000000001,15.2409,7.75777,15.0615,7.5785L12.733,5.25L12.026,5.957L13.5026,7.43359L6.5,7.43359L6.5,8.433589999999999L13.4994,8.433589999999999L12.026,9.907L12.733,10.614L15.0615,8.285499999999999L15.1005,8.242Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
