/**
 * @file DocumentSearch 搜索
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'document-search',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '6c144ae7'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '6c144ae7' + ')'}
            >
                <g>
                    <path
                        d="M11.5,2.5L11.5,3.5L1.5,3.5L1.5,2.5L11.5,2.5ZM6,5.5L6,6.5L1.5,6.5L1.5,5.5L6,5.5ZM6,11.5L6,12.5L1.5,12.5L1.5,11.5L6,11.5ZM5,8.5L5,9.5L1.5,9.5L1.5,8.5L5,8.5ZM13.322,11.674C13.5012,11.4971,13.7839,11.48104,13.982,11.6365L14.029,11.6785L15.692,13.3625C15.8769,13.5504,15.8843,13.8495,15.7087,14.0462C15.5332,14.2429,15.2351,14.2695,15.0275,14.107L14.9805,14.065L13.3175,12.381C13.1235,12.18451,13.1256,11.86801,13.322,11.674Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M10.75,5C8.40279,4.999999694824,6.5,6.9027899999999995,6.5,9.25C6.5,11.59721,8.40279,13.5,10.75,13.5C13.09721,13.5,15,11.59721,15,9.25C15,6.9027899999999995,13.09721,4.999999694824,10.75,5ZM10.75,6C12.54537,5.99938,14.00112,7.4546399999999995,14.00112,9.25C14.00112,11.045359999999999,12.54537,12.50062,10.75,12.5C8.95551,12.49938,7.50112,11.04449,7.50112,9.25C7.50112,7.45551,8.95551,6.00062,10.75,6Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
