/**
 * @file Environment 环境2
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'environment',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '1a5b8b5e'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '1a5b8b5e' + ')'}
            >
                <g>
                    <path
                        d="M1,3.5L1,10.5C1,11.6046,1.8954309999999999,12.5,3,12.5L13,12.5C14.1046,12.5,15,11.6046,15,10.5L15,3.5C15,2.395431,14.1046,1.5,13,1.5L3,1.5C1.8954309999999999,1.5,1,2.395431,1,3.5ZM2.29289,11.20711Q2,10.91421,2,10.5L2,3.5Q2,3.0857900000000003,2.29289,2.79289Q2.5857900000000003,2.5,3,2.5L13,2.5Q13.4142,2.5,13.7071,2.79289Q14,3.0857900000000003,14,3.5L14,10.5Q14,10.91421,13.7071,11.20711Q13.4142,11.5,13,11.5L3,11.5Q2.5857900000000003,11.5,2.29289,11.20711ZM4,10L4,8C4,5.79086,5.79086,4,8,4L12,4L12,6C12,8.20914,10.20914,10,8,10L4,10ZM9.34169,5.52563Q6.83769,6.3603,5,8.19246L5,8Q5,6.75736,5.87868,5.87868Q6.75736,5,8,5L11,5L11,6Q11,7.24264,10.12132,8.12132Q9.24264,9,8,9L5.60809,9Q7.31293,7.25598,9.65792,6.47432L9.34169,5.52563ZM12,13.5L12,14.5L4,14.5L4,13.5L12,13.5Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
