/**
 * @file FileList 文件列表
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'file-list',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
        >
            <defs>
                <linearGradient
                    x1="0.5"
                    y1="0"
                    x2="0.5"
                    y2="1.9507722854614258"
                    id={props.id + 'bd9ade01'}
                >
                    <stop
                        offset="0%"
                        stop-color="#007FFF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="41.57117009162903%"
                        stop-color="#004C98"
                        stop-opacity="1"
                    />
                </linearGradient>
                <linearGradient
                    x1="0.5"
                    y1="0"
                    x2="0.5"
                    y2="1.1709567308425903"
                    id={props.id + '07858b23'}
                >
                    <stop
                        offset="0%"
                        stop-color="#1087FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="100%"
                        stop-color="#C4FFF5"
                        stop-opacity="1"
                    />
                </linearGradient>
                <linearGradient
                    x1="0.5"
                    y1="0"
                    x2="0.6300838589668274"
                    y2="0.39367204904556274"
                    id={props.id + '0eb97bc3'}
                >
                    <stop
                        offset="0%"
                        stop-color="#82B4FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="100%"
                        stop-color="#6BFFF5"
                        stop-opacity="0"
                    />
                </linearGradient>
            </defs>
            <g>
                <g style={{opacity: 0}}>
                    <rect
                        x="0"
                        y="0"
                        width="24"
                        height="24"
                        rx="0"
                        fill="#D8D8D8"
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <rect
                        x="2"
                        y="5"
                        width="20"
                        height="15"
                        rx="2"
                        fill="#E6F3FF"
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M2,6L2,10C2,11.104569999999999,2.895431,12,4,12L13.114,12C14.5104,12,15.477,10.605260000000001,14.9867,9.29775L13.4867,5.29775C13.1939,4.517146,12.4477,4,11.614,4L4,4C2.895431,4,2,4.895431,2,6Z"
                        fill={'url(#' + props.id + 'bd9ade01' + ')'}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <rect
                        x="2"
                        y="7"
                        width="20"
                        height="13"
                        rx="2"
                        fill={'url(#' + props.id + '07858b23' + ')'}
                        fill-opacity="1"
                    />
                    <rect
                        x="2.25"
                        y="7.25"
                        width="19.5"
                        height="12.5"
                        rx="1.75"
                        stroke={'url(#' + props.id + '0eb97bc3' + ')'}
                        fill-opacity="0"
                        fill="none"
                        stroke-width={props.strokeWidth}
                    />
                </g>
            </g>
        </svg>
    )
);
