/**
 * @file FileOne 文件
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'file-one',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
        >
            <defs>
                <linearGradient
                    x1="0.5"
                    y1="0"
                    x2="0.5"
                    y2="1.1709567308425903"
                    id={props.id + 'bb13cc03'}
                >
                    <stop
                        offset="0%"
                        stop-color="#198CFF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="100%"
                        stop-color="#C4FFF5"
                        stop-opacity="1"
                    />
                </linearGradient>
                <linearGradient
                    x1="0.5"
                    y1="0"
                    x2="0.6045245811009974"
                    y2="0.40034522176482956"
                    id={props.id + '5609ce4a'}
                >
                    <stop
                        offset="0%"
                        stop-color="#82B4FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="100%"
                        stop-color="#6BFFF5"
                        stop-opacity="0"
                    />
                </linearGradient>
            </defs>
            <g>
                <g style={{opacity: 0}}>
                    <rect
                        x="0"
                        y="0"
                        width="24"
                        height="24"
                        rx="0"
                        fill="#D8D8D8"
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M4,5L4,19C4,20.1046,4.895431,21,6,21L18,21C19.104599999999998,21,20,20.1046,20,19L20,12L20,8.34981C20,7.80676,19.7792,7.28706,19.3883,6.91012L15.9144,3.560312C15.5416,3.200857,15.044,3,14.5261,3L12,3L6,3C4.895431,3,4,3.895431,4,5Z"
                        fill={'url(#' + props.id + 'bb13cc03' + ')'}
                        fill-opacity="1"
                    />
                    <path
                        d="M4,5L4,19C4,20.1046,4.895431,21,6,21L18,21C19.104599999999998,21,20,20.1046,20,19L20,8.34981C20,7.80676,19.7792,7.28706,19.3883,6.91012L15.9144,3.560312C15.5416,3.200857,15.044,3,14.5261,3L6,3C4.895431,3,4,3.895431,4,5ZM4.5,5L4.5,19Q4.5,19.6213,4.93934,20.0607Q5.37868,20.5,6,20.5L18,20.5Q18.621299999999998,20.5,19.0607,20.0607Q19.5,19.6213,19.5,19L19.5,8.34981Q19.5,7.71245,19.0412,7.27004L15.5673,3.9202339999999998Q15.1315,3.5,14.5261,3.5L6,3.5Q5.37868,3.5,4.93934,3.93934Q4.5,4.37868,4.5,5Z"
                        fill-rule="evenodd"
                        fill={'url(#' + props.id + '5609ce4a' + ')'}
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <rect
                        x="8"
                        y="8"
                        width="6"
                        height="1"
                        rx="0"
                        fill="#FEFEFF"
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <rect
                        x="8"
                        y="11"
                        width="6"
                        height="1"
                        rx="0"
                        fill="#FEFEFF"
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <rect
                        x="8"
                        y="14"
                        width="4"
                        height="1"
                        rx="0"
                        fill="#FEFEFF"
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
