/**
 * @file FillSquareCheck 选中
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'fill-square-check',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + 'b5759d97'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + 'b5759d97' + ')'}
            >
                <g>
                    <path
                        d="M3.38462,2L12.6154,2C13.3801,2,14,2.619913,14,3.38462L14,12.6154C14,13.3801,13.3801,14,12.6154,14L3.38462,14C2.619913,14,2,13.3801,2,12.6154L2,3.38462C2,2.619913,2.619913,2,3.38462,2ZM7.94583,10.47546L12.7201,5.5L11.31836,5.5L7.58228,8.793700000000001L5.57812,7.10876L4.080080000000001,7.10876L6.87474,10.43973C7.15006,10.76788,7.64926,10.78454,7.94583,10.47546Z"
                        fill-rule="evenodd"
                        fill="#0D1118"
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
