/**
 * @file FillLock 锁定
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'fill-lock',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '8959e193'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '8959e193' + ')'}
            >
                <g>
                    <path
                        d="M4.5,4C4.5,2.067,6.067,0.5,8,0.5C9.933,0.5,11.5,2.067,11.5,4L11.5,5L12.5,5C13.3284,5,14,5.67157,14,6.5L14,14C14,14.8284,13.3284,15.5,12.5,15.5L3.5,15.5C2.671573,15.5,2,14.8284,2,14L2,6.5C2,5.67157,2.671573,5,3.5,5L4.5,5L4.5,4ZM5.5,5L10.5,5L10.5,4C10.5,2.66162,9.44578,1.56067,8.1085,1.5025L8,1.5C6.61929,1.5,5.5,2.61929,5.5,4L5.5,5ZM8.5,9L8.5,11.5L7.5,11.5L7.5,9L8.5,9Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
