/**
 * @file FillLog 记录
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'fill-log',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '85102a92'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '85102a92' + ')'}
            >
                <g>
                    <path
                        d="M9.786999999999999,1C10.167,1,10.5325,1.1385,10.817,1.387L10.892,1.4575L13.542,4.1075C13.811,4.3765,13.972,4.7325,13.997,5.1095L14,5.213L14,13.4375C14,14.2661,13.3532,14.9506,12.526,14.9975L12.4375,15L3.5625,15C2.7339320000000003,15,2.0494305,14.3532,2.0025,13.526L2,13.4375L2,2.5625C1.99999542236,1.733932,2.646762,1.0494299,3.474,1.0025L3.5625,1L9.7875,1L9.786999999999999,1ZM9.5,9L5,9L5,10L9.5,10L9.5,9ZM8,6.501L5,6.501L5,7.501L8,7.501L8,6.501ZM9.75,1.8535C9.611930000000001,1.8535,9.5,1.965428,9.5,2.1035L9.5,4.9285L9.504,4.995C9.536999999999999,5.2795,9.778500000000001,5.5,10.0715,5.5L12.8965,5.5C12.9977,5.49998,13.0888,5.43899,13.1275,5.3455C13.1661,5.25201,13.1446,5.14444,13.073,5.073L9.927,1.927C9.88007,1.879945,9.81639,1.8535,9.75,1.8535Z"
                        fill="#0D1118"
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
