/**
 * @file Homepage 首页
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'homepage',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
        >
            <defs>
                <linearGradient
                    x1="0.6672566533088684"
                    y1="-0.5060058832168579"
                    x2="0.2416876238590574"
                    y2="1.032976530850613"
                    id={props.id + '29725766'}
                >
                    <stop
                        offset="0%"
                        stop-color="#1DD4FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="94.81717348098755%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                </linearGradient>
            </defs>
            <g>
                <g style={{opacity: 0}}>
                    <rect
                        x="0"
                        y="0"
                        width="24"
                        height="24"
                        rx="0"
                        fill="#D8D8D8"
                        fill-opacity="1"
                    />
                </g>
                <g style={{opacity: 0}}>
                    <rect
                        x="0"
                        y="0"
                        width="24"
                        height="24"
                        rx="0"
                        fill="#D8D8D8"
                        fill-opacity="1"
                    />
                </g>
                <g>
                    <path
                        d="M3,10.7L3,18.8C3,20.5673,4.43269,22,6.2,22L17.8,22C19.5673,22,21,20.5673,21,18.8L21,10.7C21,8.932690000000001,19.5673,7.5,17.8,7.5L12,7.5L6.2,7.5C4.43269,7.5,3,8.932690000000001,3,10.7Z"
                        fill={'url(#' + props.id + '29725766' + ')'}
                        fill-opacity="1"
                    />
                </g>
                <g style={{opacity: 0.9599999785423279}}>
                    <path
                        d="M1.92,8.559999999999999C1.30495,9.02129,1.63119,10,2.4,10L21.6,10C22.3688,10,22.695,9.02129,22.08,8.559999999999999L13.92,2.44C12.7822,1.586667,11.2178,1.586667,10.08,2.44L1.92,8.559999999999999Z"
                        fill="#AED6FF"
                        fill-opacity="1"
                    />
                </g>
                <g
                    transform="matrix(0,1,-1,0,26.9208984375,0.9970703125)"
                >
                    <path
                        d="M15.9531240625,14.708984375C15.9531240625,15.123194375,15.6173340625,15.458984375,15.2031240625,15.458984375L13.7119140625,15.458984375C13.2977000625,15.458984375,12.9619140625,15.123194375,12.9619140625,14.708984375C12.9619140625,14.294770375,13.2977000625,13.958984375,13.7119140625,13.958984375L15.2031240625,13.958984375C15.6173340625,13.958984375,15.9531240625,14.294770375,15.9531240625,14.708984375"
                        fill={props.colors[2]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
