/**
 * @file OperationCopy 复制
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'operation-copy',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + 'df6ce760'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + 'df6ce760' + ')'}
            >
                <g>
                    <path
                        d="M13.75,9.5L12.375,9.5L12.375,10.5L13.75,10.5Q14.2678,10.5,14.6339,10.13388Q15,9.76777,15,9.25L15,2.25Q15,1.732233,14.6339,1.366117Q14.2678,1,13.75,1L6.75,1Q6.23223,1,5.86612,1.366117Q5.5,1.732233,5.5,2.25L5.5,3.625L6.5,3.625L6.5,2.25Q6.5,2,6.75,2L13.75,2Q14,2,14,2.25L14,9.25Q14,9.5,13.75,9.5ZM1.5,13.25L1.5,6.25Q1.5,5.73223,1.866117,5.36612Q2.232233,5,2.75,5L9.75,5Q10.26777,5,10.63388,5.36612Q11,5.73223,11,6.25L11,13.25Q11,13.7678,10.63388,14.1339Q10.26777,14.5,9.75,14.5L2.75,14.5Q2.232234,14.5,1.866117,14.1339Q1.5,13.7678,1.5,13.25ZM2.5,13.25Q2.5,13.5,2.75,13.5L9.75,13.5Q10,13.5,10,13.25L10,6.25Q10,6,9.75,6L2.75,6Q2.5,6,2.5,6.25L2.5,13.25Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
