/**
 * @file ProjectOne 项目
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'project-one',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 24.0703125 24.0703125"
        >
            <defs>
                <linearGradient
                    x1="0.8458201289176941"
                    y1="-0.07086315006017685"
                    x2="0.19947824491686084"
                    y2="1.1436623407605147"
                    id={props.id + '650681bb'}
                >
                    <stop
                        offset="0%"
                        stop-color="#1DD4FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="43.90795826911926%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="100%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                </linearGradient>
                <filter
                    id={props.id + 'e7a20121'}
                    filterUnits="objectBoundingBox"
                    color-interpolation-filters="sRGB"
                    x="0"
                    y="0"
                    width="1"
                    height="1"
                >
                    <feFlood
                        flood-opacity="0"
                        result="BackgroundImageFix"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                    />
                    <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="2.0459940433502197"
                    />
                    <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_foregroundBlur"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_foregroundBlur"
                        result="shape"
                    />
                </filter>
                <filter
                    id={props.id + '131bae8a'}
                    filterUnits="objectBoundingBox"
                    color-interpolation-filters="sRGB"
                    x="-0.5925925717227909"
                    y="-2"
                    width="2.185185143445582"
                    height="6.333333333333333"
                >
                    <feFlood
                        flood-opacity="0"
                        result="BackgroundImageFix"
                    />
                    <feColorMatrix
                        in="SourceAlpha"
                        type="matrix"
                        values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                    />
                    <feOffset
                        dy="1.0029382705688477"
                        dx="0"
                    />
                    <feGaussianBlur
                        stdDeviation="1.0029382705688477"
                    />
                    <feColorMatrix
                        type="matrix"
                        values="0 0 0 0 0.04019173979759216 0 0 0 0 0.3445005416870117 0 0 0 0 0.648809552192688 0 0 0 0.23999999463558197 0"
                    />
                    <feBlend
                        mode="normal"
                        in2="BackgroundImageFix"
                        result="effect1_dropShadow"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_dropShadow"
                        result="shape"
                    />
                </filter>
                <filter
                    id={props.id + '282a690a'}
                    filterUnits="objectBoundingBox"
                    color-interpolation-filters="sRGB"
                    x="-0.7999999239295774"
                    y="-2"
                    width="2.599999847859155"
                    height="6.333333333333333"
                >
                    <feFlood
                        flood-opacity="0"
                        result="BackgroundImageFix"
                    />
                    <feColorMatrix
                        in="SourceAlpha"
                        type="matrix"
                        values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                    />
                    <feOffset
                        dy="1.0029382705688477"
                        dx="0"
                    />
                    <feGaussianBlur
                        stdDeviation="1.0029382705688477"
                    />
                    <feColorMatrix
                        type="matrix"
                        values="0 0 0 0 0.04019173979759216 0 0 0 0 0.3445005416870117 0 0 0 0 0.648809552192688 0 0 0 0.23999999463558197 0"
                    />
                    <feBlend
                        mode="normal"
                        in2="BackgroundImageFix"
                        result="effect1_dropShadow"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_dropShadow"
                        result="shape"
                    />
                </filter>
            </defs>
            <g>
                <g>
                    <g style={{opacity: 0}}>
                        <rect
                            x="0"
                            y="0"
                            width="24.070518493652344"
                            height="24.070518493652344"
                            rx="0"
                            fill="#D8D8D8"
                            fill-opacity="1"
                        />
                    </g>
                    <g>
                        <path
                            d="M21.89364921875,8.3948284375L21.893949218750002,10.2800784375L21.893949218750002,16.347848437499998C21.893949218750002,18.1203484375,20.45704921875,19.5572484375,18.68454921875,19.5572484375L9.245479218749999,19.5572484375C8.42767221875,19.5572484375,7.74798321875,19.0558484375,7.61072081875,18.3959484375C7.59952461875,18.3421484375,7.59473791875,18.286548437500002,7.59100929875,18.231748437500002C7.58730364875,18.1771484375,7.58544921875,18.1225484375,7.58544921875,18.0679484375L7.58544921875,7.2240484375000005C7.58544921875,5.4515484375,9.02234921875,4.0146484375,10.79484921875,4.0146484375L13.48779921875,4.0146484375L17.59674921875,4.0146484375C18.48924921875,4.0146484375,19.34134921875,4.3862694375,19.94864921875,5.0402884375L21.036149218749998,6.2115584375C21.58724921875,6.8050584375,21.89354921875,7.5849484375,21.89364921875,8.3948284375"
                            fill-rule="evenodd"
                            fill={'url(#' + props.id + '650681bb' + ')'}
                            fill-opacity="1"
                        />
                    </g>
                    <g
                        filter={'url(#' + props.id + 'e7a20121' + ')'} style={{opacity: 0.9599999785423279}}
                    >
                        <path
                            d="M13.4948515625,2.30810546875L5.1493915625,2.30810546875C3.9196835625,2.30810546875,2.9228515625,3.31338546875,2.9228515625,4.5534254687499995L2.9228515625,19.17470546875C2.9228515625,20.41470546875,3.9196835625,21.42000546875,5.1493915625,21.42000546875L17.2715515625,21.42000546875C18.501251562500002,21.42000546875,19.4977515625,20.41470546875,19.4977515625,19.17470546875L19.4977515625,8.36197546875C19.4977515625,7.76648546875,19.2635515625,7.19514546875,18.845951562499998,6.77406546875L15.0692515625,2.9657934687500003C14.6517515625,2.54472146875,14.0853515625,2.30810546875,13.4948515625,2.30810546875Z"
                            fill-rule="evenodd"
                            fill="#AED6FF"
                            fill-opacity="1"
                        />
                    </g>
                    <g
                        filter={'url(#' + props.id + '131bae8a' + ')'}
                    >
                        <path
                            d="M13.289361249999999,12.28589540625C13.289361249999999,12.701321406249999,12.952591250000001,13.03810140625,12.53716125,13.03810140625L7.27173525,13.03810140625C6.85630425,13.03810140625,6.51953125,12.701321406249999,6.51953125,12.28589540625C6.51953125,11.87046440625,6.85630425,11.53369140625,7.27173525,11.53369140625L12.53716125,11.53369140625C12.952591250000001,11.53369140625,13.289361249999999,11.87046440625,13.289361249999999,12.28589540625"
                            fill={props.colors[2]}
                            fill-opacity="1"
                        />
                    </g>
                    <g
                        filter={'url(#' + props.id + '282a690a' + ')'}
                    >
                        <path
                            d="M11.53422125,8.27417665625C11.53422125,8.689602656249999,11.19745125,9.02638265625,10.78202125,9.02638265625L7.27173525,9.02638265625C6.85630425,9.02638265625,6.51953125,8.689602656249999,6.51953125,8.27417665625C6.51953125,7.85874565625,6.85630425,7.52197265625,7.27173525,7.52197265625L10.78202125,7.52197265625C11.19745125,7.52197265625,11.53422125,7.85874565625,11.53422125,8.27417665625"
                            fill={props.colors[2]}
                            fill-opacity="1"
                        />
                    </g>
                </g>
            </g>
        </svg>
    )
);
