/**
 * @file ProjectMember 项目成员
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'project-member',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 24 24"
        >
            <defs>
                <linearGradient
                    x1="0.6672566533088684"
                    y1="-0.5060058832168579"
                    x2="-0.17673179645750633"
                    y2="0.6698366343972055"
                    id={props.id + 'fdbc8753'}
                >
                    <stop
                        offset="0%"
                        stop-color="#1DD4FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="94.81717348098755%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                </linearGradient>
                <filter
                    id={props.id + 'cf076015'}
                    filterUnits="objectBoundingBox"
                    color-interpolation-filters="sRGB"
                    x="0"
                    y="0"
                    width="1"
                    height="1"
                >
                    <feFlood
                        flood-opacity="0"
                        result="BackgroundImageFix"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                    />
                    <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="2.0399999618530273"
                    />
                    <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect1_foregroundBlur"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect1_foregroundBlur"
                        result="shape"
                    />
                </filter>
            </defs>
            <g>
                <g>
                    <g style={{opacity: 0}}>
                        <rect
                            x="0"
                            y="0"
                            width="24"
                            height="24"
                            rx="0"
                            fill={props.colors[2]}
                            fill-opacity="1"
                        />
                    </g>
                    <g style={{opacity: 0}}>
                        <rect
                            x="0"
                            y="0"
                            width="24"
                            height="24"
                            rx="0"
                            fill={props.colors[2]}
                            fill-opacity="1"
                        />
                    </g>
                    <g>
                        <g>
                            <path
                                d="M3,20.86614C3,21.492350000000002,3.507645,22,4.13386,22L19.8661,22C20.4924,22,21,21.492350000000002,21,20.86614C21,16.52179,17.4782,13,13.1339,13L10.86614,13C6.52179,13,3,16.52179,3,20.86614Z"
                                fill={'url(#' + props.id + 'fdbc8753' + ')'}
                                fill-opacity="1"
                            />
                        </g>
                        <g
                            filter={'url(#' + props.id + 'cf076015' + ')'} style={{opacity: 0.9599999785423279}}
                        >
                            <ellipse
                                cx="12"
                                cy="8.5"
                                rx="6.5"
                                ry="6.5"
                                fill="#AED6FF"
                                fill-opacity="1"
                            />
                        </g>
                        <g>
                            <rect
                                x="9"
                                y="7"
                                width="1.5"
                                height="3"
                                rx="0.75"
                                fill={props.colors[2]}
                                fill-opacity="1"
                            />
                        </g>
                        <g>
                            <rect
                                x="13.5"
                                y="7"
                                width="1.5"
                                height="3"
                                rx="0.75"
                                fill={props.colors[2]}
                                fill-opacity="1"
                            />
                        </g>
                    </g>
                </g>
            </g>
        </svg>
    )
);
