/**
 * @file StatusLoading 加载中
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'status-loading',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 68 22"
        >
            <defs>
                <linearGradient
                    x1="1"
                    y1="0.5"
                    x2="0.024097779765725136"
                    y2="0.5"
                    id={props.id + '7ec5efef'}
                >
                    <stop
                        offset="0%"
                        stop-color="#24E185"
                        stop-opacity="1"
                    />
                    <stop
                        offset="100%"
                        stop-color="#A8FF51"
                        stop-opacity="1"
                    />
                </linearGradient>
            </defs>
            <g>
                <g>
                    <g>
                        <rect
                            x="0"
                            y="7"
                            width="68"
                            height="8"
                            rx="4"
                            fill="#E6FCF7"
                            fill-opacity="1"
                        />
                    </g>
                    <g>
                        <rect
                            x="2"
                            y="9"
                            width="34"
                            height="4"
                            rx="2"
                            fill={'url(#' + props.id + '7ec5efef' + ')'}
                            fill-opacity="1"
                        />
                    </g>
                </g>
            </g>
        </svg>
    )
);
