/**
 * @file SymbolSubtraction 减
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'symbol-subtraction',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '05cc1580'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '05cc1580' + ')'}
            >
                <g>
                    <rect
                        x="4"
                        y="7"
                        width="8"
                        height="2"
                        rx="0"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
