/**
 * @file SymbolCloseBold 关闭加粗
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'symbol-close-bold',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '0a900720'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '0a900720' + ')'}
            >
                <g>
                    <path
                        d="M9.06054203125,8.000122031250001L12.06592203125,4.99475203125L11.00526203125,3.93409085274L7.99988203125,6.939462031250001L4.99463203125,3.93420410125L3.93396878225,4.99486203125L6.93922203125,8.000122031250001L3.93418979625,11.00516203125L4.99485203125,12.06582203125L7.99988203125,9.06078203125L11.00503203125,12.06593203125L12.06569203125,11.00527203125L9.06054203125,8.000122031250001Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
