/**
 * @file SymbolEnter 回车
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'symbol-enter',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + 'cce01cff'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + 'cce01cff' + ')'}
            >
                <g>
                    <path
                        d="M10.0334,8.89332L10.0334,3.9439450000000003C10.0334,3.422624,10.47363,3,11.01669,3C11.55974,3,12,3.422624,12,3.9439450000000003L12,10.781189999999999L5.75991,10.781189999999999L6.39405,11.38941C6.77814,11.75777,6.778,12.3551,6.39381,12.72356C6.00965,13.092,5.38686,13.0922,5.002800000000001,12.72381L2,9.84374L5.0038599999999995,6.962680000000001C5.38805,6.5942,6.01083,6.59408,6.39488,6.9624299999999995C6.77892,7.3308,6.77882,7.92812,6.39464,8.29659L5.77247,8.89332L10.0334,8.89332Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
