/**
 * @file SymbolToggle 切换
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'symbol-toggle',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + 'b44cbc81'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + 'b44cbc81' + ')'}
            >
                <g>
                    <path
                        d="M4.1756734375,3.293468933L4.9086734375,3.97346875L3.3956734375,5.6029687500000005L14.2502234375,5.6029687500000005L14.2502234375,6.6029687500000005L2.2501754375000003,6.6029687500000005C1.8326750375,6.6029687500000005,1.6066754375,6.12696875,1.8476750375,5.80596875L1.8836754375,5.762968750000001L4.1756734375,3.293468933L4.1756734375,3.293468933ZM11.8237234375,12.02846875L11.0906734375,11.34846875L12.6037234375,9.71896875L1.7491749575,9.71896875L1.7491749575,8.71896875L13.7492234375,8.71896875C14.1667234375,8.71896875,14.3927234375,9.194968750000001,14.1517234375,9.515968749999999L14.1157234375,9.55896875L11.8237234375,12.02846875L11.8237234375,12.02846875Z"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
