/**
 * @file SymbolCheck 对号
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'symbol-check',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '633ba11d'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '633ba11d' + ')'}
            >
                <g>
                    <path
                        d="M13.73310546875,5.10009765625L7.76537546875,11.319377656250001C7.39465546875,11.70572765625,6.77066546875,11.684907656250001,6.42651546875,11.27472765625L2.93310546875,7.1109976562499995L4.80578546875,7.1109976562499995L7.31077546875,9.21717765625L11.98100546875,5.10009765625L13.73310546875,5.10009765625Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
