/**
 * @file SymbolPlus 加
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'symbol-plus',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + '3b768e92'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + '3b768e92' + ')'}
            >
                <g
                    transform="matrix(0.7071067690849304,0.7071067690849304,-0.7071067690849304,0.7071067690849304,3.93413607776165,-4.997844383120537)"
                >
                    <path
                        d="M13.12646,6.31604L16.13184,3.31067L15.07118,2.25000882149L12.0658,5.255380000000001L9.06055,2.25012207L7.999886751,3.3107800000000003L11.00514,6.31604L8.000107765,9.32108L9.06077,10.38174L12.0658,7.3767L15.07095,10.38185L16.131610000000002,9.32119L13.12646,6.31604Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
