/**
 * @file SymbolLongRight 向右
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'symbol-long-right',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 16 16"
        >
            <defs>
                <clipPath
                    id={props.id + 'b4e519fd'}
                >
                    <rect
                        x="0"
                        y="0"
                        width="16"
                        height="16"
                        rx="0"
                    />
                </clipPath>
            </defs>
            <g
                clip-path={'url(#' + props.id + 'b4e519fd' + ')'}
            >
                <g>
                    <path
                        d="M13.79720078125,8.57793C14.09350078125,8.20684,14.06190078125,7.67519,13.72360078125,7.34098L9.33309078125,3L9.33301078125,5L11.31936078125,7.23438L1.75830078125,7.23438L1.75830078125,8.6344L11.43602078125,8.6344L9.33301078125,11L9.33309078125,13L13.72360078125,8.65902L13.79720078125,8.57793Z"
                        fill-rule="evenodd"
                        fill={props.colors[0]}
                        fill-opacity="1"
                    />
                </g>
            </g>
        </svg>
    )
);
