/**
 * @file WorkComputer 工作台
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import {ISvgIconProps, IconHelper, IconWrapper} from '../runtime';

export default IconWrapper(
    'work-computer',
    true,
    (h: IconHelper, props: ISvgIconProps) => (
        <svg
            fill="none"
            width={props.size}
            height={props.size}
            viewBox="0 0 27 27"
        >
            <defs>
                <linearGradient
                    x1="0.7445204257965088"
                    y1="1.1484732627868652"
                    x2="-0.0939416911381744"
                    y2="0.599670209138138"
                    id={props.id + 'c4edfc55'}
                >
                    <stop
                        offset="0%"
                        stop-color="#1DD4FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="43.90795826911926%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="100%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                </linearGradient>
                <linearGradient
                    x1="0.7445204257965088"
                    y1="1.1484732627868652"
                    x2="-0.017570015285474968"
                    y2="0.2762009286271422"
                    id={props.id + 'c7212299'}
                >
                    <stop
                        offset="0%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="52.85714268684387%"
                        stop-color="#0280FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="100%"
                        stop-color="#1DD4FF"
                        stop-opacity="1"
                    />
                </linearGradient>
                <filter
                    id={props.id + '607658b2'}
                    filterUnits="objectBoundingBox"
                    color-interpolation-filters="sRGB"
                    x="0"
                    y="0"
                    width="1"
                    height="1"
                >
                    <feFlood
                        flood-opacity="0"
                        result="BackgroundImageFix"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="BackgroundImageFix"
                        result="shape"
                    />
                    <feColorMatrix
                        in="SourceAlpha"
                        type="matrix"
                        result="hardAlpha"
                        values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                    />
                    <feOffset
                        dy="-0.5625"
                        dx="0"
                    />
                    <feGaussianBlur
                        stdDeviation="2.25"
                    />
                    <feComposite
                        in2="hardAlpha"
                        operator="arithmetic"
                        k2="-1"
                        k3="1"
                    />
                    <feColorMatrix
                        type="matrix"
                        values="0 0 0 0 0.10594630986452103 0 0 0 0 0.6988450884819031 0 0 0 0 1 0 0 0 0.42004650831222534 0"
                    />
                    <feBlend
                        mode="normal"
                        in2="shape"
                        result="effect1_innerShadow"
                    />
                    <feColorMatrix
                        in="SourceAlpha"
                        type="matrix"
                        result="hardAlpha"
                        values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
                    />
                    <feOffset
                        dy="1.125"
                        dx="0"
                    />
                    <feGaussianBlur
                        stdDeviation="2.25"
                    />
                    <feComposite
                        in2="hardAlpha"
                        operator="arithmetic"
                        k2="-1"
                        k3="1"
                    />
                    <feColorMatrix
                        type="matrix"
                        values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0.5 0"
                    />
                    <feBlend
                        mode="normal"
                        in2="effect1_innerShadow"
                        result="effect2_innerShadow"
                    />
                    <feGaussianBlur
                        in="BackgroundImageFix"
                        stdDeviation="2"
                    />
                    <feComposite
                        in2="SourceAlpha"
                        operator="in"
                        result="effect3_foregroundBlur"
                    />
                    <feBlend
                        mode="normal"
                        in="SourceGraphic"
                        in2="effect3_foregroundBlur"
                        result="shape"
                    />
                </filter>
                <radialGradient
                    cx="0"
                    cy="0"
                    r="1"
                    gradientUnits="userSpaceOnUse"
                    id={props.id + '3f5573ad'}
                    gradientTransform="translate(11.42013144493103 15.51394259929657) rotate(137.39278730831444) scale(15.339464317080644 21.655714329996204)"
                >
                    <stop
                        offset="0%"
                        stop-color="#86DEFF"
                        stop-opacity="0.7300000190734863"
                    />
                    <stop
                        offset="41.42921268939972%"
                        stop-color="#EFFDFF"
                        stop-opacity="0.25999999046325684"
                    />
                    <stop
                        offset="100%"
                        stop-color="#C9FCFF"
                        stop-opacity="0.5600000023841858"
                    />
                </radialGradient>
                <linearGradient
                    x1="0.41974887251853943"
                    y1="1"
                    x2="0.130939781665802"
                    y2="-0.19338415563106537"
                    id={props.id + '933e3dbb'}
                >
                    <stop
                        offset="2.142857201397419%"
                        stop-color="#EBF9FF"
                        stop-opacity="1"
                    />
                    <stop
                        offset="45.31651437282562%"
                        stop-color="#81D7FF"
                        stop-opacity="0.8886361718177795"
                    />
                    <stop
                        offset="100%"
                        stop-color="#BFEBFF"
                        stop-opacity="0.7874696254730225"
                    />
                </linearGradient>
            </defs>
            <g>
                <g>
                    <g style={{opacity: 0}}>
                        <rect
                            x="0"
                            y="0"
                            width="27"
                            height="27"
                            rx="0"
                            fill="#D8D8D8"
                            fill-opacity="1"
                        />
                    </g>
                    <g>
                        <path
                            d="M13.98951,16.582123L20.7576,23.23647C21.3958,23.86395,20.9515,24.949550000000002,20.0565,24.949550000000002L6.85718,24.949550000000002C5.97447,24.949550000000002,5.52468,23.889319999999998,6.13812,23.2546L12.56937,16.600249C12.95551,16.200714,13.5933,16.192574,13.98951,16.582123"
                            fill-rule="evenodd"
                            fill={'url(#' + props.id + 'c4edfc55' + ')'}
                            fill-opacity="1"
                        />
                    </g>
                    <g>
                        <rect
                            x="4.5"
                            y="7.875"
                            width="18"
                            height="12"
                            rx="1"
                            fill={'url(#' + props.id + 'c7212299' + ')'}
                            fill-opacity="1"
                        />
                    </g>
                    <g
                        filter={'url(#' + props.id + '607658b2' + ')'}
                    >
                        <rect
                            x="1.5"
                            y="2.875"
                            width="24"
                            height="17"
                            rx="3.5999999046325684"
                            fill={'url(#' + props.id + '3f5573ad' + ')'}
                            fill-opacity="1"
                        />
                        <rect
                            x="1.5"
                            y="2.875"
                            width="24"
                            height="17"
                            rx="3.5999999046325684"
                            stroke={'url(#' + props.id + '933e3dbb' + ')'}
                            fill-opacity="0"
                            fill="none"
                            stroke-width={props.strokeWidth}
                        />
                    </g>
                </g>
            </g>
        </svg>
    )
);
