/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Hello VuePress1",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-17c4ea2e",
      "path": "/"
    },
    {
      "title": "基本使用",
      "frontmatter": {},
      "regularPath": "/guide/components/official.html",
      "relativePath": "guide/components/official.md",
      "key": "v-29ed73ed",
      "path": "/guide/components/official.html",
      "headers": [
        {
          "level": 2,
          "title": "基本使用",
          "slug": "基本使用"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/started.html",
      "relativePath": "guide/started.md",
      "key": "v-39ac65e0",
      "path": "/guide/started.html"
    }
  ],
  "themeConfig": {
    "logo": "https://excalidraw.com/apple-touch-icon.png"
  }
}